# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.provider :libvirt do |libvirt|
    libvirt.driver = 'kvm'
    libvirt.cpu_mode = 'host-passthrough'
    libvirt.cpu_fallback = 'forbid'
    libvirt.graphics_type = 'none'
    libvirt.video_type = 'qxl'
    libvirt.channel :type => 'unix', :target_name => 'org.qemu.guest_agent.0', :target_type => 'virtio'
    libvirt.channel :type => 'spicevmc', :target_name => 'com.redhat.spice.0', :target_type => 'virtio'
    libvirt.input :type => 'tablet', :bus => 'usb'
    (1..3).each do
      libvirt.redirdev :type => 'spicevmc'
    end
    libvirt.random :model => 'random'
  end
  config.vm.synced_folder '.', '/vagrant', disabled: true
end
